import { Link } from "react-router-dom";
import OnlyAnonymous from "../../components/OnlyAnonymous";

export default function LandingPage() {
    return (
        <main>
            <h1><span className="human">Human</span>or<span className="ai">AI</span></h1>
            <p>
                Can you guess which quote was generated by a human and which was
                AI generated?
            </p>
            <p>Believe so? Start <Link to="/vote">NOW</Link></p>
            <OnlyAnonymous>
                <p>
                    Already have an account? <Link to="/login">login</Link> to get started.
                </p>
                <p>
                    Never been here before? <Link to="/register">Register</Link> a new account to get started.
                </p>
            </OnlyAnonymous>
        </main>
    );
}
