name: 'Run test on commit'
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        version: 19
        distribution: adopt
      - run: mvn compile
    
